In [1]:
# 実務で使えるコード
# 参考になる書籍のページやサイトを載せておく

目次
- 主成分分析
- 因子分析
- グラフィカルモデリング
- ベイジアンネットワーク

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

## 主成分分析

- やりたいこと
    - aaa
    - bbb
- 活用方法
    - aaa
    - bbb

In [4]:
iris = datasets.load_iris()


# 'sepal length (cm)' : がく片長
# 'sepal width (cm)'  : がく片幅
# 'petal length (cm)' : 花びら長
# 'petal width (cm)'  : 花びら幅

print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
data = datasets.load_iris()['data']
# 先頭5分のデータ
print(data[:5, :])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


ざっくりと数理のまとめ